//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Contracts
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PlayerLocation", Namespace = "http://schemas.datacontract.org/2004/07/Data_Contracts")]
    public partial class PlayerLocation : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int ColumnField;

        private int IDField;

        private int RowField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Column
        {
            get
            {
                return this.ColumnField;
            }
            set
            {
                this.ColumnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Row
        {
            get
            {
                return this.RowField;
            }
            set
            {
                this.RowField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IGalaxyStationService", CallbackContract = typeof(IGalaxyStationServiceCallback))]
public interface IGalaxyStationService
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IGalaxyStationService/ClearPlayers")]
    void ClearPlayers();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IGalaxyStationService/RegisterPlayer", ReplyAction = "http://tempuri.org/IGalaxyStationService/RegisterPlayerResponse")]
    int RegisterPlayer(int column, int row);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IGalaxyStationService/RemovePlayer")]
    void RemovePlayer(int playerID);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IGalaxyStationService/UpdatePlayersLocation")]
    void UpdatePlayersLocation(int playerID, int column, int row);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGalaxyStationServiceCallback
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IGalaxyStationService/PlayerLocationsCallback")]
    void PlayerLocationsCallback(Data_Contracts.PlayerLocation[] playerLocations);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGalaxyStationServiceChannel : IGalaxyStationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GalaxyStationServiceClient : System.ServiceModel.DuplexClientBase<IGalaxyStationService>, IGalaxyStationService
{

    public GalaxyStationServiceClient(System.ServiceModel.InstanceContext callbackInstance) :
        base(callbackInstance)
    {
    }

    public GalaxyStationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
        base(callbackInstance, endpointConfigurationName)
    {
    }

    public GalaxyStationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public GalaxyStationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public GalaxyStationServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, binding, remoteAddress)
    {
    }

    public void ClearPlayers()
    {
        base.Channel.ClearPlayers();
    }

    public int RegisterPlayer(int column, int row)
    {
        return base.Channel.RegisterPlayer(column, row);
    }

    public void RemovePlayer(int playerID)
    {
        base.Channel.RemovePlayer(playerID);
    }

    public void UpdatePlayersLocation(int playerID, int column, int row)
    {
        base.Channel.UpdatePlayersLocation(playerID, column, row);
    }
}
